[versions]
agp = "8.13.1"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
lifecycleViewModel = "2.8.7"
activityCompose = "1.11.0"
composeBom = "2025.11.00"
firebaseCrashlyticsBuildtools = "3.0.6"
hilt = "2.51.1"
hiltCompose = "1.3.0"
coil = "2.7.0"
material3Android = "1.4.0"
ksp = "2.0.21-1.0.25"
volley = "1.2.1"
material = "1.12.0"
material_ver = "1.4.0"
material_icon_ver = "1.7.8"

[libraries]
androidx-core-ktx = { group="androidx.core", name="core-ktx", version.ref="coreKtx" }
androidx-lifecycle-runtime-ktx = { group="androidx.lifecycle", name="lifecycle-runtime-ktx", version.ref="lifecycleRuntimeKtx" }
androidx-activity-compose = { group="androidx.activity", name="activity-compose", version.ref="activityCompose" }
androidx-compose-bom = { group="androidx.compose", name="compose-bom", version.ref="composeBom" }
androidx-compose-ui = { group="androidx.compose.ui", name="ui" }
androidx-compose-ui-graphics = { group="androidx.compose.ui", name="ui-graphics" }
androidx-compose-ui-tooling-preview = { group="androidx.compose.ui", name="ui-tooling-preview" }
androidx-compose-material3 = { group="androidx.compose.material3", name="material3" }
material-lat = { group = "androidx.compose.material3" , name= "material3", version.ref = "material_ver"}
material-icon = { group = "androidx.compose.material" , name= "material-icons-extended", version.ref = "material_icon_ver"}

androidx-compose-ui-test-junit4 = { group="androidx.compose.ui", name="ui-test-junit4" }


#FireBase
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
# Coil
coil = { module="io.coil-kt:coil-compose", version.ref="coil" }

# Hilt
hilt-android = { group="com.google.dagger", name="hilt-android", version.ref="hilt" }
# Compiler for @AndroidEntryPoint (required!!)
hilt-android-compiler = { group="com.google.dagger", name="hilt-android-compiler", version.ref="hilt" }
# Compiler for @Module/@InstallIn (optional but recommended)
hilt-compiler = { group="com.google.dagger", name="hilt-compiler", version.ref="hilt" }


hilt-navigation-compose = { group="androidx.hilt", name="hilt-navigation-compose", version.ref="hiltCompose" }

# ViewModel Compose
lifecycle-viewmodel-compose = { group="androidx.lifecycle", name="lifecycle-viewmodel-compose", version.ref="lifecycleViewModel" }

# Tests
junit = { group="junit", name="junit", version.ref="junit" }
androidx-junit = { group="androidx.test.ext", name="junit", version.ref="junitVersion" }
androidx-espresso-core = { group="androidx.test.espresso", name="espresso-core", version.ref="espressoCore" }
androidx-compose-ui-tooling = { group="androidx.compose.ui", name="ui-tooling" }
androidx-compose-ui-test-manifest = { group="androidx.compose.ui", name="ui-test-manifest" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id="com.android.application", version.ref="agp" }
kotlin-android = { id="org.jetbrains.kotlin.android", version.ref="kotlin" }
kotlin-compose = { id="org.jetbrains.kotlin.plugin.compose", version.ref="kotlin" }
hilt = { id="com.google.dagger.hilt.android", version.ref="hilt" }
ksp = { id="com.google.devtools.ksp", version.ref="ksp" }
